[4.x] Document hex_to_rgb modifier
statamic/docs pull request #1259
Opened 2024-02-27 16:39 UTC by DanielDarrenJones

This PR adds basic documentation for the hex_to_rgb modifier added in https://github.com/statamic/cms/pull/9582 closes #1257.

2024-02-27 16:45 UTC, jasonvarga requested changes
I'd make these modifications but apparently I don't have permission.

2024-02-27 16:45 UTC, jasonvarga commented on content/collections/modifiers/hex_to_rgb.md
> +duplicated_from: 2d555b32-e68c-4f9b-8570-f2e8d185989b
Can you please remove this line.

2024-02-27 16:45 UTC, jasonvarga commented on content/collections/modifiers/hex_to_rgb.md
> +color: #FF269E
Please wrap this in single quotes otherwise it's a comment.

2024-02-27 16:48 UTC, DanielDarrenJones commented on content/collections/modifiers/hex_to_rgb.md
> +color: #FF269E
That makes sense, wondered why some most things didn't have it, but the color fields did!

2024-02-27 16:48 UTC, DanielDarrenJones commented
@jasonvarga should all be updated now

2024-03-08 11:59 UTC, duncanmcclean approved these changes

2024-03-08 11:59 UTC, merged