Update encrypt cookies docs
statamic/docs pull request #1427
Opened 2024-08-05 10:13 UTC by jacksleight

2024-08-05 10:16 UTC, duncanmcclean requested changes

2024-08-05 10:16 UTC, duncanmcclean commented on content/collections/tags/cookie.md
> +To prevent encryption you need to [add an exception](https://laravel.com/docs/11.x/responses#cookies-and-encryption) to the EncryptCookies middleware.
Instead of linking out to the Laravel docs here, it might be better if we add an example on this page.

Also, since we still support Laravel 10, we'll need to keep the "add an exception to EncryptCookies.php" bit.

2024-08-05 10:40 UTC, jacksleight commented on content/collections/tags/cookie.md
> +To prevent encryption you need to [add an exception](https://laravel.com/docs/11.x/responses#cookies-and-encryption) to the EncryptCookies middleware.
Ah yeah, good point. I will tweak.

2024-08-06 13:06 UTC, duncanmcclean approved these changes
Thanks!

2024-08-06 13:06 UTC, merged