Fix 'days_ago' not properly display
statamic/docs pull request #632
Opened 2021-12-12 16:58 UTC by zunnurs01

Fix and add example for 'days_ago' modifier.

2022-01-06 21:54 UTC, Konafets requested changes

2022-01-06 21:54 UTC, Konafets commented on content/collections/modifiers/days_ago.md
> +//Example previous date
```suggestion
// Example previous date
```

2022-01-06 21:54 UTC, Konafets commented on content/collections/modifiers/days_ago.md
> +//Example current date on your server:
```suggestion
// Example current date on your server:
```

2022-01-06 21:54 UTC, Konafets commented on content/collections/modifiers/days_ago.md
> +//Antlers Frontend
```suggestion
// Antlers Frontend
```

2022-01-06 21:54 UTC, Konafets commented on content/collections/modifiers/days_ago.md
> +//Output:
```suggestion
// Output:
```

2022-01-06 21:56 UTC, Konafets commented
Tried the changes and beside the missing space, it looks fine for me. It also removes the `{{ noparse }}` output.

![2022-01-06_22-51-56](https://user-images.githubusercontent.com/363363/148457738-351bd541-9e62-400b-bccf-eca31e55939d.jpg)

2022-01-26 15:39 UTC, merged

2022-01-26 15:39 UTC, jackmcdade commented
Thanks!